name: DevOps RAG Model
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        

      - name: Run sample command
        run: |
          echo "Starting pipeline..." > pipeline.log
          echo "Running buid stage ..." >> pipeline.log
          echo "Docker build failed ...">>pipeline.log
      - name: show files
        run: ls -a
      - name: failur
        run: exit 1
      - name: upload logs
        if : always()
        uses: actions/upload-artifact@v4
        with:
          name: pipeline-logs
          path: pipeline.log
