name: DevOps RAG Model

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run sample command
        run: echo "pipeline running"

      - name: Sample error
        run: exit 1